server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./data/devdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: "device-mgmt-internship-case-secret-idk-123"
    expiration-ms: 3600000   # 1 hour
  cors:
    allowed-origins: "http://localhost:3000"
